// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prosjekt.Data;

#nullable disable

namespace Prosjekt.Migrations
{
    [DbContext(typeof(ProsjektContext))]
    partial class ProsjektContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "Admin",
                            ConcurrencyStamp = "admin",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "Mekanisk",
                            ConcurrencyStamp = "Mekanisk",
                            Name = "Mekanisk",
                            NormalizedName = "MEKANISK"
                        },
                        new
                        {
                            Id = "Hydraulisk",
                            ConcurrencyStamp = "Hydraulisk",
                            Name = "Hydraulisk",
                            NormalizedName = "HYDRAULISK"
                        },
                        new
                        {
                            Id = "Elektro",
                            ConcurrencyStamp = "Elektro",
                            Name = "Elektro",
                            NormalizedName = "ELEKTRO"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Prosjekt.Entities.ChecklistModel", b =>
                {
                    b.Property<string>("DocID_str")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SerialNr_str")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Bearing_drum")
                        .HasColumnType("int");

                    b.Property<int>("Brake_cylinder_and_replace_seals")
                        .HasColumnType("int");

                    b.Property<string>("Brake_force")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");



                    b.Property<int>("Check_Brakes")
                        .HasColumnType("int");

                    b.Property<int>("Clutch_Plate")
                        .HasColumnType("int");

in

                    b.Property<int>("HOil_gearbox")
                        .HasColumnType("int");

                    b.Property<int>("Hoses")
                        .HasColumnType("int");

                    b.Property<int>("Hydraulic_block")
                        .HasColumnType("int");

                    b.Property<int>("Hydraulic_cylinder")
                        .HasColumnType("int");

                    b.Property<int>("Oil_tank")
                        .HasColumnType("int");

                    b.Property<int>("PTO_and_storage")
                        .HasColumnType("int");

                    b.Property<int>("Pinion_bearing")
                        .HasColumnType("int");

                    b.Property<string>("Prepared_by_str")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Procedure_str")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Ringe_cylinder_and_replace_seals")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Starting_Date")
                        .HasColumnType("date");

                    b.Property<int>("Test_radio")
                        .HasColumnType("int");

                    b.Property<string>("Test_winch")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Traction_force_Kn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Type_str")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Wedge_on_sprocket")
                        .HasColumnType("int");

                    b.Property<int>("Wire")
                        .HasColumnType("int");

                    b.Property<int>("Wiring_on_winch")
                        .HasColumnType("int");

                    b.Property<string>("comment_str")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<string>("xx_Bar_str")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("DocID_str", "SerialNr_str");

                    b.HasIndex("SerialNr_str")
                        .IsUnique();

                    b.ToTable("Checklist");
                });

            modelBuilder.Entity("Prosjekt.Entities.ChecklistSignatureModel", b =>
                {
                    b.Property<string>("DocID_str")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EmployeeID_int")
                        .HasColumnType("varchar(255)");

                    b.HasKey("DocID_str", "EmployeeID_int");

                    b.HasIndex("DocID_str")
                        .IsUnique();

                    b.HasIndex("EmployeeID_int")
                        .IsUnique();

                    b.ToTable("Checklist_signature");
                });

            modelBuilder.Entity("Prosjekt.Entities.CustomerModel", b =>
                {
                    b.Property<int>("ID_int")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email_str")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName_str")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName_str")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Phone_str")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Postal_Code_str")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Street_Address_str")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID_int");

                    b.HasIndex("Postal_Code_str");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Prosjekt.Entities.CustomerProductModel", b =>
                {
                    b.Property<int>("CustomerID_int")
                        .HasColumnType("int");

                    b.Property<string>("SerialNr_str")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("WarrantyID_int")
                        .HasColumnType("int");

                    b.HasKey("CustomerID_int", "SerialNr_str");

                    b.HasAlternateKey("SerialNr_str");

                    b.HasAlternateKey("WarrantyID_int");

                    b.ToTable("Customer_Product");
                });

            modelBuilder.Entity("Prosjekt.Entities.EmployeeUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FirstName_str")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("LastName_str")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Level_str")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("RememberMe")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Prosjekt.Entities.EquipmentModel", b =>
                {
                    b.Property<int>("Id_int")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Availability")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name_str")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_int");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("Prosjekt.Entities.PartsModel", b =>
                {
                    b.Property<int>("PartID_int")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EquipmentID_int")
                        .HasColumnType("int");

                    b.Property<string>("PartName_str")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Quantity_available_int")
                        .HasColumnType("int");

                    b.HasKey("PartID_int");

                    b.HasIndex("EquipmentID_int")
                        .IsUnique();

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("Prosjekt.Entities.PostalCode", b =>
                {
                    b.Property<string>("Postal_Code_str")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("City_str")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Country_str")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("State_str")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Postal_Code_str");

                    b.ToTable("Postal_Code");
                });

            modelBuilder.Entity("Prosjekt.Entities.ProductModel", b =>
                {
                    b.Property<string>("SerialNr_str")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Model_Year")
                        .HasColumnType("int");

                    b.Property<string>("ProductName_str")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Product_Type_str")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("SerialNr_str");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Prosjekt.Entities.ReplacedPartsReturnedModel", b =>
                {
                    b.Property<int>("PartID_int")
                        .HasColumnType("int");

                    b.Property<int>("FormID_int")
                        .HasColumnType("int");

                    b.Property<int>("Quantity_int")
                        .HasColumnType("int");

                    b.HasKey("PartID_int", "FormID_int");

                    b.HasIndex("FormID_int")
                        .IsUnique();

                    b.ToTable("Replaced_Parts_Returned");
                });

            modelBuilder.Entity("Prosjekt.Entities.ServiceFormEmployeeModel", b =>
                {
                    b.Property<int>("FormID_int")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeID_int")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Repair_Description_str")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Working_Hours_int")
                        .HasColumnType("int");

                    b.HasKey("FormID_int", "EmployeeID_int");

                    b.HasIndex("EmployeeID_int")
                        .IsUnique();

                    b.HasIndex("FormID_int")
                        .IsUnique();

                    b.ToTable("Service_Form_Employee");
                });

            modelBuilder.Entity("Prosjekt.Entities.ServiceFormModel", b =>
                {
                    b.Property<int>("FormID_int")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateOnly>("AgreedDelivery_date")
                        .HasColumnType("date");

                    b.Property<int>("BookedServiceWeek_int")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ProductRecived_date")
                        .HasColumnType("date");

                    b.Property<string>("Repairdescription_str")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly>("ServiceCompleted_date")
                        .HasColumnType("date");

                    b.Property<string>("ShippingMethod_str")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("FormID_int");

                    b.ToTable("Service_Form");
                });

            modelBuilder.Entity("Prosjekt.Entities.ServiceFormSignModel", b =>
                {
                    b.Property<int>("FormID_int")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeID_int")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("CustomerID_int")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Sign_Date")
                        .HasColumnType("date");

                    b.HasKey("FormID_int", "EmployeeID_int", "CustomerID_int");

                    b.HasIndex("CustomerID_int")
                        .IsUnique();

                    b.HasIndex("EmployeeID_int")
                        .IsUnique();

                    b.HasIndex("FormID_int")
                        .IsUnique();

                    b.ToTable("Service_Form_Sign");
                });

            modelBuilder.Entity("Prosjekt.Entities.ServiceOrderModel", b =>
                {
                    b.Property<int>("OrderID_int")
                        .HasColumnType("int");

                    b.Property<int>("CustomerID_int")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description_From_Customer_str")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Order_type_str")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly>("Received_Date")
                        .HasColumnType("date");

                    b.Property<string>("SerialNr_str")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("OrderID_int", "CustomerID_int");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Service_ordre");
                });

            modelBuilder.Entity("Prosjekt.Entities.ServiceOrderServiceformModel", b =>
                {
                    b.Property<int>("OrderID_int")
                        .HasColumnType("int");

                    b.Property<int>("FormID_int")
                        .HasColumnType("int");

                    b.HasKey("OrderID_int");

                    b.HasIndex("FormID_int")
                        .IsUnique();

                    b.ToTable("Service_Order_Service_form");
                });

            modelBuilder.Entity("Prosjekt.Entities.UsedPartModel", b =>
                {
                    b.Property<int>("PartID_int")
                        .HasColumnType("int");

                    b.Property<int>("FormID_int")
                        .HasColumnType("int");

                    b.Property<int>("Quantity_int")
                        .HasColumnType("int");

                    b.HasKey("PartID_int", "FormID_int");

                    b.HasIndex("FormID_int")
                        .IsUnique();

                    b.ToTable("Used_Parts");
                });

            modelBuilder.Entity("Prosjekt.Entities.WarrantyModel", b =>
                {
                    b.Property<int>("ID_int")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("WarrantyName_str")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ID_int");

                    b.ToTable("Warranty");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Prosjekt.Entities.EmployeeUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Prosjekt.Entities.EmployeeUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prosjekt.Entities.EmployeeUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Prosjekt.Entities.EmployeeUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Prosjekt.Entities.ChecklistModel", b =>
                {
                    b.HasOne("Prosjekt.Entities.ProductModel", "product")
                        .WithOne("Checklist")
                        .HasForeignKey("Prosjekt.Entities.ChecklistModel", "SerialNr_str")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");
                });

            modelBuilder.Entity("Prosjekt.Entities.ChecklistSignatureModel", b =>
                {
                    b.HasOne("Prosjekt.Entities.ChecklistModel", "Checklist")
                        .WithOne("ChecklistSignature")
                        .HasForeignKey("Prosjekt.Entities.ChecklistSignatureModel", "DocID_str")
                        .HasPrincipalKey("Prosjekt.Entities.ChecklistModel", "DocID_str")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prosjekt.Entities.EmployeeUser", "employee")
                        .WithOne("ChecklistSignature")
                        .HasForeignKey("Prosjekt.Entities.ChecklistSignatureModel", "EmployeeID_int")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Checklist");

                    b.Navigation("employee");
                });

            modelBuilder.Entity("Prosjekt.Entities.CustomerModel", b =>
                {
                    b.HasOne("Prosjekt.Entities.PostalCode", "Address")
                        .WithMany("customers")
                        .HasForeignKey("Postal_Code_str")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Prosjekt.Entities.CustomerProductModel", b =>
                {
                    b.HasOne("Prosjekt.Entities.CustomerModel", "Customer")
                        .WithMany("CustomerProducts")
                        .HasForeignKey("CustomerID_int")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prosjekt.Entities.ProductModel", "Product")
                        .WithOne("CustomerProduct")
                        .HasForeignKey("Prosjekt.Entities.CustomerProductModel", "SerialNr_str")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prosjekt.Entities.WarrantyModel", "Warranty")
                        .WithOne("CustomerProduct")
                        .HasForeignKey("Prosjekt.Entities.CustomerProductModel", "WarrantyID_int")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");

                    b.Navigation("Warranty");
                });

            modelBuilder.Entity("Prosjekt.Entities.PartsModel", b =>
                {
                    b.HasOne("Prosjekt.Entities.EquipmentModel", "Equipment")
                        .WithOne("Parts")
                        .HasForeignKey("Prosjekt.Entities.PartsModel", "EquipmentID_int")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("Prosjekt.Entities.ReplacedPartsReturnedModel", b =>
                {
                    b.HasOne("Prosjekt.Entities.ServiceFormModel", "ServiceForm")
                        .WithOne("ReplacedPartsReturned")
                        .HasForeignKey("Prosjekt.Entities.ReplacedPartsReturnedModel", "FormID_int")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prosjekt.Entities.PartsModel", "Parts")
                        .WithMany("ReplacedPartsReturned")
                        .HasForeignKey("PartID_int")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parts");

                    b.Navigation("ServiceForm");
                });

            modelBuilder.Entity("Prosjekt.Entities.ServiceFormEmployeeModel", b =>
                {
                    b.HasOne("Prosjekt.Entities.EmployeeUser", "Employee")
                        .WithOne("EmployeeForm")
                        .HasForeignKey("Prosjekt.Entities.ServiceFormEmployeeModel", "EmployeeID_int")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prosjekt.Entities.ServiceFormModel", "ServiceForm")
                        .WithOne("Employee")
                        .HasForeignKey("Prosjekt.Entities.ServiceFormEmployeeModel", "FormID_int")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("ServiceForm");
                });

            modelBuilder.Entity("Prosjekt.Entities.ServiceFormSignModel", b =>
                {
                    b.HasOne("Prosjekt.Entities.CustomerModel", "Customer")
                        .WithOne("ServiceFormSign")
                        .HasForeignKey("Prosjekt.Entities.ServiceFormSignModel", "CustomerID_int")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prosjekt.Entities.EmployeeUser", "Employee")
                        .WithOne("Sign")
                        .HasForeignKey("Prosjekt.Entities.ServiceFormSignModel", "EmployeeID_int")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prosjekt.Entities.ServiceFormModel", "ServiceForm")
                        .WithOne("Sign")
                        .HasForeignKey("Prosjekt.Entities.ServiceFormSignModel", "FormID_int")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Employee");

                    b.Navigation("ServiceForm");
                });

            modelBuilder.Entity("Prosjekt.Entities.ServiceOrderModel", b =>
                {
                    b.HasOne("Prosjekt.Entities.CustomerProductModel", "CustomerProductModel")
                        .WithOne("ServiceOrders")
                        .HasForeignKey("Prosjekt.Entities.ServiceOrderModel", "CustomerId")
                        .HasPrincipalKey("Prosjekt.Entities.CustomerProductModel", "CustomerID_int")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prosjekt.Entities.CustomerModel", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("CustomerProductModel");
                });

            modelBuilder.Entity("Prosjekt.Entities.ServiceOrderServiceformModel", b =>
                {
                    b.HasOne("Prosjekt.Entities.ServiceFormModel", "serviceForm")
                        .WithOne("OrderServiceformModel")
                        .HasForeignKey("Prosjekt.Entities.ServiceOrderServiceformModel", "FormID_int")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prosjekt.Entities.ServiceOrderModel", "ServiceOrder")
                        .WithOne("OrderServiceformModel")
                        .HasForeignKey("Prosjekt.Entities.ServiceOrderServiceformModel", "OrderID_int")
                        .HasPrincipalKey("Prosjekt.Entities.ServiceOrderModel", "OrderID_int")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceOrder");

                    b.Navigation("serviceForm");
                });

            modelBuilder.Entity("Prosjekt.Entities.UsedPartModel", b =>
                {
                    b.HasOne("Prosjekt.Entities.ServiceFormModel", "ServiceForm")
                        .WithOne("UsedPart")
                        .HasForeignKey("Prosjekt.Entities.UsedPartModel", "FormID_int")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prosjekt.Entities.PartsModel", "Parts")
                        .WithMany("UsedParts")
                        .HasForeignKey("PartID_int")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parts");

                    b.Navigation("ServiceForm");
                });

            modelBuilder.Entity("Prosjekt.Entities.ChecklistModel", b =>
                {
                    b.Navigation("ChecklistSignature");
                });

            modelBuilder.Entity("Prosjekt.Entities.CustomerModel", b =>
                {
                    b.Navigation("CustomerProducts");

                    b.Navigation("ServiceFormSign")
                        .IsRequired();
                });

            modelBuilder.Entity("Prosjekt.Entities.CustomerProductModel", b =>
                {
                    b.Navigation("ServiceOrders")
                        .IsRequired();
                });

            modelBuilder.Entity("Prosjekt.Entities.EmployeeUser", b =>
                {
                    b.Navigation("ChecklistSignature")
                        .IsRequired();

                    b.Navigation("EmployeeForm")
                        .IsRequired();

                    b.Navigation("Sign")
                        .IsRequired();
                });

            modelBuilder.Entity("Prosjekt.Entities.EquipmentModel", b =>
                {
                    b.Navigation("Parts")
                        .IsRequired();
                });

            modelBuilder.Entity("Prosjekt.Entities.PartsModel", b =>
                {
                    b.Navigation("ReplacedPartsReturned");

                    b.Navigation("UsedParts");
                });

            modelBuilder.Entity("Prosjekt.Entities.PostalCode", b =>
                {
                    b.Navigation("customers");
                });

            modelBuilder.Entity("Prosjekt.Entities.ProductModel", b =>
                {
                    b.Navigation("Checklist")
                        .IsRequired();

                    b.Navigation("CustomerProduct")
                        .IsRequired();
                });

            modelBuilder.Entity("Prosjekt.Entities.ServiceFormModel", b =>
                {
                    b.Navigation("Employee")
                        .IsRequired();

                    b.Navigation("OrderServiceformModel")
                        .IsRequired();

                    b.Navigation("ReplacedPartsReturned")
                        .IsRequired();

                    b.Navigation("Sign")
                        .IsRequired();

                    b.Navigation("UsedPart")
                        .IsRequired();
                });

            modelBuilder.Entity("Prosjekt.Entities.ServiceOrderModel", b =>
                {
                    b.Navigation("OrderServiceformModel")
                        .IsRequired();
                });

            modelBuilder.Entity("Prosjekt.Entities.WarrantyModel", b =>
                {
                    b.Navigation("CustomerProduct")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
